name: Build
on:
  push:
    branches:
      - actions-test
jobs:
  build_macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build mac binary
      run: cargo build --release
